# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ocr_request.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ocr_request.proto',
  package='ocr_request',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11ocr_request.proto\x12\x0bocr_request\"\x15\n\x06urlMsg\x12\x0b\n\x03url\x18\x01 \x01(\t\"B\n\x0c\x41piResponse2\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x15\n\x08response\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_response2H\n\rocrApiService\x12\x37\n\x05goURL\x12\x13.ocr_request.urlMsg\x1a\x19.ocr_request.ApiResponse2b\x06proto3'
)




_URLMSG = _descriptor.Descriptor(
  name='urlMsg',
  full_name='ocr_request.urlMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='ocr_request.urlMsg.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=55,
)


_APIRESPONSE2 = _descriptor.Descriptor(
  name='ApiResponse2',
  full_name='ocr_request.ApiResponse2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='ocr_request.ApiResponse2.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response', full_name='ocr_request.ApiResponse2.response', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_response', full_name='ocr_request.ApiResponse2._response',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=57,
  serialized_end=123,
)

_APIRESPONSE2.oneofs_by_name['_response'].fields.append(
  _APIRESPONSE2.fields_by_name['response'])
_APIRESPONSE2.fields_by_name['response'].containing_oneof = _APIRESPONSE2.oneofs_by_name['_response']
DESCRIPTOR.message_types_by_name['urlMsg'] = _URLMSG
DESCRIPTOR.message_types_by_name['ApiResponse2'] = _APIRESPONSE2
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

urlMsg = _reflection.GeneratedProtocolMessageType('urlMsg', (_message.Message,), {
  'DESCRIPTOR' : _URLMSG,
  '__module__' : 'ocr_request_pb2'
  # @@protoc_insertion_point(class_scope:ocr_request.urlMsg)
  })
_sym_db.RegisterMessage(urlMsg)

ApiResponse2 = _reflection.GeneratedProtocolMessageType('ApiResponse2', (_message.Message,), {
  'DESCRIPTOR' : _APIRESPONSE2,
  '__module__' : 'ocr_request_pb2'
  # @@protoc_insertion_point(class_scope:ocr_request.ApiResponse2)
  })
_sym_db.RegisterMessage(ApiResponse2)



_OCRAPISERVICE = _descriptor.ServiceDescriptor(
  name='ocrApiService',
  full_name='ocr_request.ocrApiService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=125,
  serialized_end=197,
  methods=[
  _descriptor.MethodDescriptor(
    name='goURL',
    full_name='ocr_request.ocrApiService.goURL',
    index=0,
    containing_service=None,
    input_type=_URLMSG,
    output_type=_APIRESPONSE2,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OCRAPISERVICE)

DESCRIPTOR.services_by_name['ocrApiService'] = _OCRAPISERVICE

# @@protoc_insertion_point(module_scope)
